name: Live Server and Test

on:
  push:
#     branches: [ main, release ]
#   pull_request:
#     branches: [ main ]

jobs:
  deploy-and-test:
    uses: ./.github/workflows/common.yml
    with:
      SERVER_URL: https://jsonplaceholder.typicode.com
      AZURE_FUNCTION_URL: http://localhost:7071
