name: Start Mock Server and Test

on:
  push:
#     branches: [ main, develop ]
#   pull_request:
#     branches: [ main ]

jobs:
  build-and-test:
    uses: ./.github/workflows/common.yml
    with:
      SERVER_URL: http://localhost:3000
      AZURE_FUNCTION_URL: http://localhost:7071
