name: Start Mock Server and Test

on:
  push:
#     branches: [ main, develop ]
#   pull_request:
#     branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: mock-server/package-lock.json

      - name: Build and start mock server
        run: |
          echo "Starting mock server..."
          cd mock-server
          npm ci
          npm run build
          nohup npm run start & # Run the mock server in the background
          cd ..

      - name: Wait for mock server to be ready
        run: |
          echo "Waiting for mock server to be ready..."
          timeout=120
          while [ $timeout -gt 0 ]; do
            if curl -f http://localhost:3000/health; then
              echo "Mock server is ready!"
              break
            fi
            echo "Waiting for mock server... ($timeout seconds remaining)"
            sleep 5
            timeout=$((timeout-5))
          done

          if [ $timeout -le 0 ]; then
            echo "Mock server failed to start within timeout"
            exit 1
          fi

      - name: Test mock server endpoints
        run: |
          echo "Testing mock server endpoints..."
          curl -f http://localhost:3000/health
          curl -f http://localhost:3000/api/todos
          curl -f http://localhost:3000/api/products
          curl -f http://localhost:3000/api/orders
          curl -X POST -H "Content-Type: application/json" \
            -d '{"name":"Test User","email":"test@example.com"}' \
            http://localhost:3000/api/users
          echo "All mock server tests passed!"

      - name: Install Azure Functions Core Tools
        run: |
          echo "Installing Azure Functions Core Tools..."
          npm install -g azure-functions-core-tools@4 --unsafe-perm

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Build and start Azure Function
        run: |
          echo "Starting Azure Function..."
          cd SimpleAzureFunction
          dotnet build
          API_URL=http://localhost:3000/api/todos func start &
          cd ..

      - name: Wait for Azure Function to be ready
        run: |
          echo "Waiting for Azure Function to be ready..."
          timeout=120
          while [ $timeout -gt 0 ]; do
            if curl -f http://localhost:7071/api/GetPublicApiData; then
              echo "Azure Function is ready!"
              break
            fi
            echo "Waiting for Azure Function... ($timeout seconds remaining)"
            sleep 5
            timeout=$((timeout-5))
          done

          if [ $timeout -le 0 ]; then
            echo "Azure Function failed to start within timeout"
            exit 1
          fi
