name: Start Mock Server and Test

on:
  push:
#     branches: [ main, develop ]
#   pull_request:
#     branches: [ main ]

jobs:
  build-and-test:
    uses: 777abhi/lt-github-workflows/.github/workflows/mock-server-azure-function.yml@feat/add-reusable-workflow-for-mock-server-azure-function-testing
    with:
      SERVER_URL: http://localhost:3000
      AZURE_FUNCTION_URL: http://localhost:7071
